### ISSUE TITLE
feat: req  consistent cursor is comming!

### ISSUE THREAD

**Issue by kRHYME7** [RAprogramm/HyDe-Themes#10]
hi @RAprogramm  

Can you add the  hyprcursor patch to the tarball?

I wrote a converter for Xcursor to patch the hyprcursor

for dracula
` Hyde --dev convert_cursor ~/.icons/Dracula-cursor `

for one-dark
`  Hyde --dev convert_cursor ~/.icons/onedark-cursor  ` 

https://github.com/kRHYME7/Hyde-cli/commit/f9ef1bf1e6f6f4b7d98e8face4f6dbfe35e68840#

After  you can compress it as a new cursor tar. Thanks! 

![image](https://github.com/RAprogramm/HyDe-Themes/assets/53417443/1885c763-892e-433f-aa5f-1ae2e25ababe)

**Comment by RAprogramm** [comment]
> hi @RAprogramm  
> 
> Can you add the  hyprcursor patch to the tarball?
> 
> I wrote a converter for Xcursor to patch the hyprcursor
> 
> for dracula
> ` Hyde --dev convert_cursor ~/.icons/Dracula-cursor `
> 
> for one-dark
> `  Hyde --dev convert_cursor ~/.icons/onedark-cursor  ` 
> 
> https://github.com/kRHYME7/Hyde-cli/commit/f9ef1bf1e6f6f4b7d98e8face4f6dbfe35e68840#
> 
> 
> 
> After  you can compress it as a new cursor tar. Thanks! 
> 
> 
> ![image](https://github.com/RAprogramm/HyDe-Themes/assets/53417443/1885c763-892e-433f-aa5f-1ae2e25ababe)
> 

Sure!

**Comment by RAprogramm** [comment]
@kRHYME7 done! check this out!

**Comment by kRHYME7** [comment]
Perfect!!!
