### ISSUE TITLE
Dracula theme missing icons 

### ISSUE THREAD

**Issue by IgorD-lab** [RAprogramm/HyDe-Themes#11]
![image](https://github.com/RAprogramm/HyDe-Themes/assets/74680803/75074f4e-5373-4e4d-b741-04ddef401351)

A lot of icons are missing from dracula theme which makes it difficult to distinguish files.

**Comment by RAprogramm** [comment]
i will try to change icons package asap

**Comment by RAprogramm** [comment]
sorry for too long.
![240607_18h06m45s_screenshot](https://github.com/RAprogramm/HyDe-Themes/assets/70325462/5a658bde-9499-478b-b11c-b1f584c15f1e)
what about this?

**Comment by IgorD-lab** [comment]
Sorry for late response it works well, I like the icon pack as well.

**Comment by RAprogramm** [comment]
> Sorry for late response it works well, I like the icon pack as well.

If it is not difficult for you - don't forget about star. Thank you
