### ISSUE TITLE
Dolphin

### ISSUE THREAD

**Issue by kRHYME7** [RAprogramm/HyDe-Themes#3]
How can we pass the gtk icons to Dolphin

**Comment by RAprogramm** [comment]
all icons are present
![240223_22h53m54s_screenshot](https://github.com/RAprogramm/hyprdots-theme/assets/70325462/2352e281-c931-4e28-8889-3af9392e7f19)
![240223_22h54m16s_screenshot](https://github.com/RAprogramm/hyprdots-theme/assets/70325462/8d8cc23a-7606-43b7-9621-7003d1face33)

we can set up icons to gtk handle by 'GTK settings' programm

![240223_22h57m40s_screenshot](https://github.com/RAprogramm/hyprdots-theme/assets/70325462/8f47bc06-06a2-436e-815d-b6d9bf4f7ccb)

**Comment by kRHYME7** [comment]
No dolphin Icons rendered on my 2 machines. can I have the tar.gz for icons that are working?

**Comment by RAprogramm** [comment]
> No dolphin Icons rendered on my 2 machines. can I have the tar.gz for icons that are working?
> 
> 
> I'll try to investigate tomorrow. 

Sure! 
Icons in `Source/arcs/` directory
