### ISSUE TITLE
Highlit color same as BG on switchers.

### ISSUE THREAD

**Issue by 3laws** [RAprogramm/HyDe-Themes#9]
Follow up of [hyde-gallery/#5](https://github.com/kRHYME7/hyde-gallery/issues/5) (thanks for the fix)

Only the font of selected item changes to black making almost indistinguishable.

# Steps to recreate:
-Use any of Hyde's switchers

_castle.jpg selected_
![image](https://github.com/RAprogramm/HyDe-Themes/assets/4267075/8118c878-75cc-4159-bdaf-26fc895718ee)

_Mac OS selected_
![image](https://github.com/RAprogramm/HyDe-Themes/assets/4267075/d0737dcd-942d-4b52-89cc-c60e1a9fa6e3)

_in this one is literally impossible to distinguish anything_
![image](https://github.com/RAprogramm/HyDe-Themes/assets/4267075/d445641b-00dc-4be2-84c6-98a13d6e1007)

_clipboard_
![image](https://github.com/RAprogramm/HyDe-Themes/assets/4267075/54d0a553-ddbb-4948-8008-15a26928a5bf)

**Comment by RAprogramm** [comment]
thank you for issue. 
i got you!

**Comment by RAprogramm** [comment]
![240517_05h33m47s_screenshot](https://github.com/RAprogramm/HyDe-Themes/assets/70325462/0d242173-8e05-4a5d-a60f-8d55e993955b)
![240517_05h34m02s_screenshot](https://github.com/RAprogramm/HyDe-Themes/assets/70325462/ee9aeb85-4511-462f-ad3a-e93c45310b2d)

check this out!

**Comment by 3laws** [comment]
Just patched it. Works fine. The change from green to purple is very welcomed! 👏
